### PR TITLE
Update advancedediting.md

### PR DESCRIPTION
**Pull request by AidenW8512**
# Pull Request

**Feel free to delete parts of this pull request template that do not apply to your pull request, this is just used as a guideline**

## Description

[Provide a concise description of the changes introduced by this pull request.]

## Related Issue(s)

[Link any related GitHub issues or pull requests here.]

## Changes Made

[List the specific changes made in this pull request.]

- [Change 1]
- [Change 2]
- ...

## Screenshots (if applicable)

[Add screenshots or gifs to showcase the changes, if relevant.]

## Checklist

- [ ] I have reviewed the [Contributing Guidelines](CONTRIBUTING.md) for this repository.
- [ ] I have followed the coding style and conventions of this project.
- [ ] I have added/updated relevant documentation (if necessary).
- [ ] The code is tested and all tests pass.
- [ ] I have updated the version (if applicable).
- [ ] All commit messages are meaningful and follow the established convention.

## Additional Notes

[Include any additional information or context that may be relevant to this pull request.]

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [LICENSE](LICENSE) for this project.

### CODE REVIEW

**Review by rcallaby — CHANGES_REQUESTED** [review]
The code is unfortunately still incorrect. To place an image in the markdown you would need to do the following:



Where obviously you have stored a ss2.png file in an images folder on your fork of the repository.

Can you please make changes to your code following the above example?

**Comment by AidenW8512** [comment]
Hello, I made some changes by putting image names in the bracket. Can you see the changes? Thank you.

**Comment by rcallaby** [comment]
I have literally shown you how to do this task. Please just do it like the above code sample I provided.

Or in case you may not have seen that:

```
![ss2.png] (./images/ss2.png)
```

IT is not about the image name, carefully study the code. There should be an images folder with the images you tried to upload before.

**Comment by AidenW8512** [comment]
Hello, I noticed the images were in private folder before, so I moved them to public  folder. Please let me know if it works now. Thanks.

**Review by rcallaby — CHANGES_REQUESTED** [review]
Please just use the code example I gave you.

I wrote:

```
![ss3.png] (./images/ss3.png)
```
You wrote
```
![ss3.png](https://github.com/AidenW8512/imagesforemacs/blob/main/ss3.png)
```

There is NO HTTP in my example. Literally it is a cut and paste of my code to make this work. Just make sure there are actual images in a ./images folder.

Please look at the updated Part 05 which was merged earlier for another example.

**Comment by AidenW8512** [comment]
Thank you. I copied and pasted the line for 3 images. The Images folder says private. Hope it works. Thanks.

**Comment by rcallaby** [comment]
I don't have the images, you need to make the images folder public so that they can be included in the merge.

You're almost there. Just fix the images issue and I can merge this pull request.

**Comment by AidenW8512** [comment]
Thanks. I found a way to make the Images folder public from the setting. Please try again and let me know.

**Comment by rcallaby** [comment]
Still no dice.

Are you adding the images folder in the commit? Because that is not included.

You need to do either:
git add .
Where there is a dot ( . ) after the add meaning add everything or something like this:
```
git add file1.txt folder/file2.txt file3.txt file4.txt file5.txt
```

**Comment by AidenW8512** [comment]
I can do all with git add . command. Do I insert this line of code in the same place (advancedediting.md) where I put paths to the 3 images? Does it matter whether i put the git add . in the beginning or the end? Then I commit the changes again? Thanks.

**Comment by rcallaby** [comment]
Here is the way you do this as I am assuming you are using Git.

Are you using Git from the command line? Seriously hope so.

First you add all the files that need to be pushed by using 
git add .

Then you commit those files using the following command:
git commit -m "Add meaningful commit message here"

Then you push that commit using:
git push origin "yourbranchname"

Where obviously yourbranchname is the name of your branch

**Comment by AidenW8512** [comment]
I think this will take me a while since I do not have git command prompt at the moment. Thanks.

**Comment by rcallaby** [comment]
How are you pushng code to my repository without git installed?

What code editor are you using?

**Comment by AidenW8512** [comment]
Can I not participate and make changes on this project?

**Comment by rcallaby** [comment]
Weird. I have been exceedingly patient with you, trying to get you to understand things. All I did was ask two simple questions and you closed the pull request?

I have never blocked anyone on github before but I am seriously considering blocking you.

**Pull request closed without merging**
